1.12. Время разбивать камни
htmlacademy-ecmascript/860419-big-trip-15 pull request #4
Opened 2021-07-28 17:21 UTC by den-mesh

2021-07-28 17:45 UTC, dtsaryov requested changes

2021-07-28 17:45 UTC, dtsaryov commented on src/view/loading.js
> +  `<p class="trip-events__msg">Loading...</p>`
ESLint

2021-07-28 17:45 UTC, dtsaryov commented on src/view/list-empty.js
> +  `<p class="trip-events__msg">Click New Event to create your first point</p>`
ESLint

2021-07-28 17:45 UTC, dtsaryov commented on public/index.html
> +<head>
А зачем отступы убрал? Revert'ни файл, пожалуйста

2021-07-28 17:45 UTC, dtsaryov commented on src/view/add-new-point.js
> +  `<ul class="trip-events__list">
Список не относится к редактированию / созданию новой точки

2021-07-28 17:45 UTC, dtsaryov commented on src/view/list-empty.js
> +  `<p class="trip-events__msg">Click New Event to create your first point</p>`
И простые шаблоны можно в одну строку:

```JS
export const createEmptyTemplate = () => '...';
```

2021-07-28 17:45 UTC, dtsaryov commented on src/view/list-empty.js
> +  `<p class="trip-events__msg">Click New Event to create your first point</p>`
Ну и тут у нас просто сообщение, а не список, а модуль почему-то называется list-empty

2021-07-28 17:45 UTC, dtsaryov commented on src/main.js
> +};
```JS
const render = (container, template, place) => container.insertAdjacentHTML(place, template);
```

Сделай перечисление RenderPlace, которое объединит все варианты, и выбери значение по умолчанию для аргумента place, чтобы можно было опустить его в некоторых местах

2021-07-28 17:45 UTC, dtsaryov commented on src/main.js
> +const siteFiltersElement = siteHeadingElement.querySelector('.trip-controls__filters');
Не смешивай объявления переменных и функций

Б14. Код всех JS-файлов соответствует рекомендованной структуре.

2021-07-28 17:45 UTC, dtsaryov commented on src/main.js
> +  siteMainElement.insertAdjacentElement('beforeend', siteEventsListElement);
Для этого нужен шаблон

2021-07-28 17:45 UTC, dtsaryov commented on src/main.js
> +  if (POINT_COUNT !== 0) {
Лучше наоборот:

```JS
if (POINT_COUNT === 0) {
  // render
  return;
}

// Основная логика
```

2021-07-29 16:34 UTC, den-mesh commented on src/main.js
> +};
Прошу уточнить. Многие вещи для меня не сразу понятны  из-за отсутствия опыта и крепкой теоретической базы. Я правильно понял, что нам тут будет нужен объект ключ-значение или нам нужен будет массив объектов?

2021-07-29 16:36 UTC, den-mesh commented on src/main.js
> +const siteFiltersElement = siteHeadingElement.querySelector('.trip-controls__filters');
не совсем понял в этом моменте. на этих 4-х строках, вроде нет функций. Только переменные

2021-07-29 16:37 UTC, den-mesh commented on public/index.html
> +<head>
Теперь не везде в готовом коде нажимать ctrl + alt + L в webstorme))

2021-07-29 16:38 UTC, den-mesh commented on src/view/loading.js
> +  `<p class="trip-events__msg">Loading...</p>`
поправил, на кавычки ругался)

2021-07-29 16:41 UTC, den-mesh commented on src/main.js
> +  siteMainElement.insertAdjacentElement('beforeend', siteEventsListElement);
ты про const newFragment = document.createDocumentFragment(); ?

2021-08-02 16:08 UTC, dtsaryov approved these changes

2021-08-02 16:08 UTC, dtsaryov commented on public/index.html
> +<head>
Не вернул изменения

2021-08-02 16:08 UTC, dtsaryov commented on src/view/point.js
> +              <div class="event">
Отступы уехали куда-то в космос

2021-08-02 16:08 UTC, dtsaryov commented on src/view/sorting.js
> +            <div class="trip-sort__item  trip-sort__item--day">
Тоже отступы бы поправить

2021-08-02 16:08 UTC, dtsaryov commented on src/view/message-form-create.js
> +export const createMessageFormTemplate = () => (
А в чем разница с no-point-message.js?

2021-08-02 16:08 UTC, merged

2021-08-02 16:39 UTC, den-mesh commented on src/view/point.js
> +              <div class="event">
> 
> 
> Отступы уехали куда-то в космос

Из космоса вернул)

2021-08-02 16:40 UTC, den-mesh commented on src/view/message-form-create.js
> +export const createMessageFormTemplate = () => (
> 
> 
> А в чем разница с no-point-message.js?

Просто нужно было убрать лишнее и почистить код. Сделал